variables:
    VERSION: $CI_COMMIT_REF_NAME-$CI_PIPELINE_ID
    BUILD_NAME: $CI_PROJECT_NAME-$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID

stages:
    - build

build:
    stage: build
    image: golang:1.10.1
    before_script: ~
    script:
        - sed -i -e "s/VERSION_CHANGE_ME/$VERSION/" main.go
        - go get -d -v
        - go build -o $BUILD_NAME
        - ls -l
        - ./$BUILD_NAME --version
    artifacts:
        name: $BUILD_NAME
        paths:
            - $BUILD_NAME
            - config.ini.sample
